export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "category/FECTH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCES: "category/FECTH_CATEGORIES_SUCCES",
  FETCH_CATEGORIES_FAILED: "category/FECTH_CATEGORIES_FAILED",
};
